### ISSUE TITLE
Where is requirements.txt?

### ISSUE THREAD

**Issue by mustardbutter** [batiscuff/proxy_machine#7]
Cant find it

**Comment by adw3r** [comment]
He is using poetry in his project.

referring to official poetry docs https://python-poetry.org/docs/basic-usage/ here is dependencies installation.
![image](https://github.com/batiscuff/proxy_machine/assets/77853696/1edd8152-69f2-4656-8a81-04e21bda13f3)

**Comment by mustardbutter** [comment]
> He is using poetry in his project.
> 
> referring to official poetry docs https://python-poetry.org/docs/basic-usage/ here is dependencies installation. ![image](https://user-images.githubusercontent.com/77853696/247282257-1edd8152-69f2-4656-8a81-04e21bda13f3.png)

thanks!
